# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - somesite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://someacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_00000000000000000000000000000000 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_00000000000000000000000000000000 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: someacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_00000000000000000000000000000000 }}/someimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/appservice-settings@v1
      with:
        app-name: 'somesite'
        slot-name: 'staging'
        app-settings-json: '[{ "WEBSITES_PORT": "8000" }]'

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'somesite'
        slot-name: 'staging'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_00000000000000000000000000000000 }}
        images: 'someacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_00000000000000000000000000000000 }}/someimage:${{ github.sha }}'

    - name: Swap staging slot into production
      id: slot_swap
      run: |
        az webapp deployment slot swap -g "some-rg" -n "somesite" -s staging

    - name: az cli logout
      run: az logout