# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ansalemo-wafc-swap-gh

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ansalemoacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d02287566f9549bfbbe91b48504c0cd7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0de3ee9b10f54bffb32916a6fe3e2f2d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ansalemoacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d02287566f9549bfbbe91b48504c0cd7 }}/linux-app-service-slot-swap-examples:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/appservice-settings@v1
      with:
        app-name: 'yoursite'
        app-settings-json: '[{ "WEBSITES_PORT": "8000" }]'

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ansalemo-wafc-swap-gh'
        slot-name: 'staging'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a52f5336aa2a49afb5fb42250ac36e18 }}
        images: 'ansalemoacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d02287566f9549bfbbe91b48504c0cd7 }}/linux-app-service-slot-swap-examples:${{ github.sha }}'
        
    - name: Swap staging slot into production
      id: slot_swap
      run: |
        az webapp deployment slot swap -g "ansalemo-rg" -n "ansalemo-wafc-swap-gh" -s staging

    - name: az cli logout
      run: az logout